# main 브랜치에 PR을 생성하면
# 테스트 -> 빌드

name: Run Test And Build After PR

on:
  pull_request:
    branches: main

jobs:
  # 1. 테스트 job
  test:
    runs-on: ubuntu-latest
    steps:
      # 코드를 가져옴
      - name: Get Codes
        uses: actions/checkout@v4

      # 의존성 파일들 설치
      - name: Install Dependencies
        run: npm install

      # 테스트 실행
      - name: Run Test
        run: npm run test

  # 2. 빌드 job
  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Get Codes
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run Build
        run: npm run build
